// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvrcts4ln4VFLp/JL2kLo6dXuvPlmypHW3bssqWe3cr8qYg8khChwQYAJSttvQ88x7zZFO4kKJESpY9",
	"6UxPVfInFEgAB+fynRv8hAMeJ5wBUxK3nnBCBIlBgTC/OkSRMZHQCwdEzfRICDIQNFGUM9zCd4x+SQHR",
	"EJiiEwoCTbhAagYodDOxh+GRxEkEuIXjhV8Yp3qFRK/rYUZi/UH29hMNsYcFfEmpgBC3lEjBwzKYQUws",
	"lUqB0PP//yPx/2j4p/dv3IN//9Tw3jdX2fjb//oRe1gtEr2+VIKyKV6tVtlqG8csHzB7gwRInopAPyQC",
	"pD4vmyKSnxNRJhVhgT5YIngCQlEwiwcCiIJPisYV6w9pDFKROEEPM2AbnEMPRCI7WTNjwkVMlOUR+GY1",
	"zSESXrNokXFo65gepuFrhFY8zC7pxeTxEthUa8X7dx6OKct+Nr2Xy+fZg8SgiN5dH+dHARPcwj/U16pb",
	"d9KsZwK7yr5feVbHSmy4ySSqXxe4sXHm7MCyvnn6Z+mVIOY0gE/2xfbet/Yt0m+3tmZpjFsf843xfdXi",
	"CQSHMuJWf6vnKKJSo5Akiq4nuPXxwPl23up++9ArD6dJ+HrVjohUyK7wWv1eFTHio2VLQVXWrOPj3yFQ",
	"2MOPPoHEz4y5ACWyyHRZfyog0UovlESpIFFRI7CHJWXTNCKiMLzGmoAl01xlfKcPfiL4nIYgamEQ1yiv",
	"5/P0YTKenw/ujKDCkGpmkmhQQBTLiU1enw/uEIkiHhA9YOwZSDDTYBXRgCDKUMAFSMQFimkUUfvrDdSm",
	"NQ+N8NEI6/9OGo14hN+WICwmj2X5XpFHGqex2fcBQqRpeO3GP59kG69NT4/hTShp+qf3HzVo/BRXobpB",
	"oQpCKTOETlMiCFPwWlqb20xa06rHXkbrlupqwg2mlpW2oBddNqVsn5cC84ElGY1wwqWaCpBfIkewA5f1",
	"eCW8ZMtdUqnKmw3IlDJttCiiUiE+KbsNWdIgBo/qU0Km8Enxz1AhpKEeNjIRoASFuXavGjP0TKRn6p0E",
	"yDRSskr02avWE6YKYnkoPuq5bjEiBFkY0eyUwBXEXCxeZpx2zj77fJ3BxXbdkh4/UDVDKaOqoLoXZ055",
	"m0dXZ87EK5X1zdXZ8uJsOTxbXtGz5QU9Ww7p2dt/ytj+tXS+ytCuCtHGjqgh8zLmXJkLt/ItiTMiY4jk",
	"bq15KjN3C99TqXiMPsPCn5Mo1TELFdLGbWQ6NaEoC9GERgrMChVnsyH2zvPo15uhyMsjPN89/bQ3+Lak",
	"yIQEFfT8mo5BMFAgUf6VDiDEOgSXiAgoRMYvCxIMG/bJvg/qgYvPL7NxNwkFnE3oNBXVepBwUQWoXCgj",
	"yhxHFTfYCgxxp63apnDr/cnJuxMjCfu7mR+DMgVTEPoccyrpmEZULfY4isJHa7egFxGMRMa1ucf7Kn7u",
	"5N2NNW25N5Gy1h/wlClcdYD1Yk7er4iFWA47eeIWcCaVIJSpsnsKkvRQf6FjM5OPZI7gsGzEfG3CcC7I",
	"FA6O3t3n21qsCc6J2KfNty5V2CENHTLnuGURmbIkVWhCIQotwhhLq1JnyMORQ47ighdt/msLO2RiZpAr",
	"s7+Jnj/NqKtXHK4X14n9DmWL+NnhkVkNTQSPTcgREEUiPkVvSBBAoiD0EOMKkUAHPWnC2dsqfBUF3T/k",
	"WLmt2OBlreqHTc4maIsHIc0ZD5v7m/t8W6ecOIvU7NWsPKHc9lVCAFPIJpw6attZWnC4M+j2O73+Bfbw",
	"zV2/b59+afcuux3s4bv+r/3r/+ljD3e6l91ht7M3ZL1dm9dWxm1f7M2S8oCkGPQ3GllMcjT8WpHTtiT2",
	"4LT9Io/om/9paYmIAqksOaXlu0JwUeHqfzlHp8cnPyOtGxElTCHQX2qITDiTgN4MBB9HEKMOKEIja/4f",
	"hsMBag968m1txEasAxPKINRWZD7Vu8vWiC3RcJEAurvpoSUaUhUBWtq5VlHQcsSWfv5vufW/+6XXqdVq",
	"dbe6rFM2JxENfSKmaazVaol6dggVho4bDVSey7jyJzxlIVqiPtc+1j4fN44rviaRDiQWPjxSqSRaorYd",
	"QPnAceO0Yl4CIqZSS8kPgVHQOwzyMZSPHTfeVcxOGUnVTEddgcmpluiuNHLcaKIqzlgXbTjiHm9BzEEg",
	"owBoiU4q2ZIyMic0ImMjoqwUtTl6YoktRAIdHsjdOtVCe1UHezgVEW7hmVKJbNVN2UMJEnwGUaOgJjUu",
	"pvWQB/WZiqO6mAR6UYf4BY8TmsXLZHxIY8KQFpehHx6TiDBr5TnIK47UjErEg8AgVABVtmMs4lkY7tqv",
	"Vh7O4axcZr3pIQETMFu5EiuVa3qs7W1Qk9fAUkH9fG4VmQk34i/v+t+31300sG/RRJCpsZBCrfeNFtn7",
	"00YT/f1v798ii4Yu19beAKRCYx4ubASA1IwoFJBUQmjpN2R7yOHRD3V9nnruMepBktZjyka4htpjqffO",
	"q3/2wAFh2pmOARGlBB2nWscVRwRJyqZRJRE6w5LWByNj+1a0ZsGa0dKcc79LzvyMO1Wl0x1ey6iqc1kB",
	"DzekQZlqvi/G4Senp8UovNGoCmOVxsAKRzTjQnlopjXWzzVWpnFMxKKK4uoK8qZ2OfkuMkFaVpuZazeb",
	"214Q+4ng2p/XplTN0nGN8t2Ii71DZ+Z4e/iUTdA9fF4JdA+fuoW4h08spEeHb5Vhqo5aDjRvDz/6Wmb+",
	"nAiTA2vh9fq/tS97nfbNxd1Vtz/EHu5fD3+5vuvrGKl9edNtd/6v+7+92+Et9vCge3PVu73tXfc73X7P",
	"hVHtu+GHbn/YO28PzUivP+ze9NuX9uVv7d5l++yyi++3w0KnRVadqwJCA4adHcjcYyGd0zAlUclyTbxF",
	"GSIoTiNF/c1gBL8I+/1K7DexJ5Wlnb8j6ldD1C1lcULaqSYVyDuw7VTEWbRwR3vgpgbPBSBJYvBNm2yb",
	"TOfJayPW1UE8MCUWyC49Bok425gyITRKBdRQH3SEBHGiFh5i+seIWT75ZokaGvLEj2AOEbKnQfAlJZE0",
	"HJ9QIZXbS7v0MQk+PxARjpiOEohyRRXLwoPq0EXrsUXVnp12tF2X9vAHIFFVK9OOZ+7LnkZxltc+yoWo",
	"yo7oOWGc0UCnyETNssytsMi64TGzlBzSCN3lcIs0F72UGdeeMGXZ83156xe4yrzEWdFtzVc9rFuXH3sn",
	"lD/LjzSpbpfeQsBZaKSnSZ0BckTk9QrNK2E9Vk73u/c6+NixabEouCvTvN3eZJzSKMzyzg0WNWuNWuPF",
	"9VbnPnI5uwsf6w0cQ17crHWyKPZm7VDWmTU2kN8dWbdqcyG+qFHrZq3M3RHKJtzUDTlTJDA1XXeDpXN+",
	"pVMhd4LNpMdFCAGPi4FDff/+5WaA3qKkGxqMYsKI6QXkPWpEGSpU1IMolQqERHNKRuw84mnYJ4rOYXBR",
	"G7GhdkbtQQ9NeBTxB4naXRMSs5CIrBTImTSF6WCBSCC4lKhAjbSwF9EAmL1M45jSTkgwA3Rk1GeTJw8P",
	"DzViXpsU0M2V9cveebd/2/WPao2azgkLETXeIBzltZJMlQcZT9qDXkHTMgVeeZgnwEhCcQu/qzVqx04r",
	"DUjVSULr8yaJkhlp1tfN/tYTnoKqAhfTrQRESu1QaQtKie2Xmlw0TUwLwFBgewS9ELfwJZWqU7hXULyE",
	"9XFXG5Cl8RiE64q6xojiSIBKBUMmrnL+PyHT/L7VlxRMmuEkE5NH25aV9A9jpvkVqxAmJI0Ubp00NlOh",
	"d0fFVKjZ0AC0ryOx8qp7vZSFtBApGXDTP0yokV9J2kN7oZ1cJHwbjszFFRtTGjEeNRqZ6erspvWESWLq",
	"f5q6uo529Nh6vUNKqqZTbpBhC13TIAApJ2kULbLGNoRrDdHKeLyXHpdL/MfL6LIVwAqCzkiYhYN27+a3",
	"27u9TruoCU6ckzB0vPt2dJSKc5qCk28phbxeJ229DtyHHs7qABYTUBEUFJkav7ceuzdpS9UdjXPTHEUE",
	"MXioLL1v4o/9vLO+wrQXgPJGShBRYCpro0CIep3SVcIa6k1MnuE8VeiNWBbcgE4BowhNgWlqABGGeh1T",
	"Zb6xyqFTLen8kXZHfvPoCOXxXK+DfJQ5EgJJLYR5vXl0VP8hQ0SfhiNWusQ43gEo5tLpWrRf94ZjJSwZ",
	"Qzzj4eKrI5JVu80btKsSEjb/pH13dDNczx7JAix+h8C/CgQeN06/HQXnnE0iGijkrwM4Ey4ZcCCxu5BC",
	"Nnowf0mgdlhbQM8qpF55u0LLLLPYE2Gmgtnyw2wj0XcJuou+S6h+AerDOk3/kyKgD3la5O3ILKlEWcq+",
	"yThXATifQfC5wDW34l6WbV7PNSyLQFXdjDTjOhTO2i7Pe0M7Z7c3rGLH+pP61t9MVMSfx2U6c6rsQaog",
	"8jtMZRQcfzsKcmxiWf/4L4lBTs2fwSDv2RR2t5Wg8QL1OlUY8ycaSuPbhifrBO17gPLd8v89LP8C1LOh",
	"h/tzpOps7ry/r4aW1+vqxj7d8jtq+YH25CgHCLnOrLIowdt50SmiEwgWQQS2imkyv8ql1idb3a/+EQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
